// generated by stringer -type MsgType; DO NOT EDIT

package tmux

import "fmt"

const (
	_MsgType_name_0 = "MsgVersion"
	_MsgType_name_1 = "MsgIdentifyFlagsMsgIdentifyTermMsgIdentifyTTYNameMsgIdentifyCWDMsgIdentifyStdinMsgIdentifyEnvironMsgIdentifyDoneMsgIdentifyClientPid"
	_MsgType_name_2 = "MsgCommandMsgDetachMsgDetachKillMsgExitMsgExitedMsgExitingMsgLockMsgReadyMsgResizeMsgShellMsgShutdownMsgStderrMsgStdinMsgStdoutMsgSuspendMsgUnlockMsgWakeup"
)

var (
	_MsgType_index_0 = [...]uint8{0, 10}
	_MsgType_index_1 = [...]uint8{0, 16, 31, 49, 63, 79, 97, 112, 132}
	_MsgType_index_2 = [...]uint8{0, 10, 19, 32, 39, 48, 58, 65, 73, 82, 90, 101, 110, 118, 127, 137, 146, 155}
)

func (i MsgType) String() string {
	switch {
	case i == 12:
		return _MsgType_name_0
	case 100 <= i && i <= 107:
		i -= 100
		return _MsgType_name_1[_MsgType_index_1[i]:_MsgType_index_1[i+1]]
	case 200 <= i && i <= 216:
		i -= 200
		return _MsgType_name_2[_MsgType_index_2[i]:_MsgType_index_2[i+1]]
	default:
		return fmt.Sprintf("MsgType(%d)", i)
	}
}
